# Travis CI Configuration File
#
# Tell Travis CI which distro to use.
dist: bionic

# Tell Travis CI what languages to use.
language: node_js

# Specify which version of NodeJS to use.
node_js: node

# Git clone depth.
# By default Travis CI clones repositories to a depth of 50 commits.
git:
  depth: 1

# Whitelist branches for the "push" build check.
branches:
  only:
    - master

# What to cache for future builds.
cache:
  directories:
    - node_modules
    - public
    - .cache

before_install:
  - npm i -g gatsby-cli

install:
  - npm install

script:
  - travis_wait 30 gatsby build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_fbaa66361ce3_key -iv $encrypted_fbaa66361ce3_iv -in gatsbyjs_blog_id_rsa.enc -out $HOME/.ssh/gatsbyjs_blog_id_rsa -d
  - openssl aes-256-cbc -K $encrypted_fbaa66361ce3_key -iv $encrypted_fbaa66361ce3_iv -in gatsbyjs_blog_id_rsa.pub.enc -out $HOME/.ssh/gatsbyjs_blog_id_rsa.pub -d
  - cat $HOME/.ssh/gatsbyjs_blog_id_rsa.pub >> $HOME/.ssh/known_hosts

deploy:
  provider: script
  script: rsync -rPhczpEt --delete -e 'ssh -p $SSH_PORT -i $HOME/.ssh/gatsbyjs_blog_id_rsa' $TRAVIS_BUILD_DIR/public/ $SSH_USER@$SSH_HOST:/home/$SSH_USER/gatsbyjs-blog/public
  skip_cleanup: true
  on:
    branch: master
