# Travis CI Configuration File
#
# Tell Travis CI which distro to use.
dist: bionic

# Tell Travis CI what languages to use.
language: node_js

# Specify which version of NodeJS to use.
node_js: node

# Git clone depth.
# By default Travis CI clones repositories to a depth of 50 commits.
git:
  depth: 1

# Whitelist branches for the "push" build check.
branches:
  only:
    - master

# What to cache for future builds.
cache:
  directories:
    - node_modules
    - public
    - .cache

before_install:
  - npm install -g gatsby-cli --silent

install:
  - npm install --silent

script:
  - travis_wait 30 gatsby build

before_deploy:
  - ssh-keyscan -p $SSH_PORT $SSH_HOST >> $HOME/.ssh/known_hosts
  - base64 --decode <<< "$SSH_KEY_PUB" >> $HOME/.ssh/id_rsa.pub
  - cat $HOME/.ssh/id_rsa.pub
  - base64 --decode <<< "$SSH_KEY_PRIV" >> $HOME/.ssh/id_rsa
  - chmod 600 $HOME/.ssh/id_rsa
    #- echo "Host $SSH_HOST\n  IdentityFile ~/.ssh/gatsbyjs_blog_id_rsa" >> $HOME/.ssh/config

deploy:
  provider: script
  script: echo 'Deploy via rsync' # rsync -rPhczpEt --delete -e "ssh -p $SSH_PORT" $TRAVIS_BUILD_DIR/public/ $SSH_USER@$SSH_HOST:/home/$SSH_USER/gatsbyjs-blog/public
  skip_cleanup: true
  on:
    branch: master
